### ISSUE TITLE
Проблема с автоматическим скачиванием

### ISSUE THREAD

**Issue by IamSVP94** [ArtIntlabs/ydown#1]
При установке флажка -d, должен запускать wget через терминал, но после выполнения команды вылетает ошибка 422

![image](https://user-images.githubusercontent.com/58026014/107024947-c5cba380-67b9-11eb-8426-d56c872d97eb.png)

**Comment by IamSVP94** [comment]
Есть питоновская библиотечка ```wget```, может через [нее](https://webfanat.com/article_id/?id=153) попробовать? Но она не предустановленная

**Comment by IamSVP94** [comment]
В [мануале ](https://yandex.ru/dev/oauth/doc/dg/concepts/about.html)было написано, что нужно создать [приложение для доступа](https://oauth.yandex.ru/client/b6058748ffe94219a086458dec436562). Я его создал, но его не применял

**Comment by IamSVP94** [comment]
Заметил что строка после ```wget``` немного короче (без параметров). Попробую с ними поиграться

**Comment by jubick1337** [comment]
fixed in dda07e132fc28a38bf7c1a17ee5aae923d8187a8
